### PR TITLE
Moved .sh files to scripts/

### PR DESCRIPTION
**Pull request by DamieFC**
Wanted to help

### CODE REVIEW

**Comment by Ayman0x03** [comment]
I don't see any helping here since we wanted it to be simple and this is against the idea

**Comment by adamtherookie** [comment]
Dunno, @Ayman0x03, why is it against the idea of simplicity?

**Comment by Ayman0x03** [comment]
Idk it needs to be on the source folder

**Comment by Ayman0x03** [comment]
And it feels better when it's in the root folder

**Comment by DamieFC** [comment]
> And it feels better when it's in the root folder

I'm trying to help organize the source. The code is everywhere else and the shell scripts go in /src/scripts.

**Comment by adamtherookie** [comment]
@Ayman0x03 I kinda agree because the shell scripts aren't actually a part of the source code. Look at the project organization of other OSes. (such as \*deep breath\* Mandelbrot) Anyway it's up to you to decide. (LOL if only we had 3 admins so we could vote)

**Comment by adamtherookie** [comment]
Anyway I'm going to reopen until we settle this.

**Comment by Ayman0x03** [comment]
No keep it like this and have fun don't stay here reopening this pull request

**Comment by Ayman0x03** [comment]
Or you know what i don't wanna be A$$hole who keeps write mean comments

**Comment by adamtherookie** [comment]
lol

**Comment by Ayman0x03** [comment]
@DamieFC make sure to edit the files so they don't ask for a file that Doesn't exist then I'll merge

**Review by adamtherookie — APPROVED** [review]

**Comment by DamieFC** [comment]
> @DamieFC make sure to edit the files so they don't ask for a file that Doesn't exist then I'll merge

Ok will do tomorrow

**Comment by DamieFC** [comment]
Tomorrow has been and gone

**Comment by Ayman0x03** [comment]
Sorry I'm off my computer for about 15 day @aa2006 take care of this pull request and wish you happy Eid 😊😊

**Review by adamtherookie — APPROVED** [review]

**Comment by adamtherookie** [comment]
OK I'm going to merge seeing that the README is updated and it breaks nothing.

**Pull request merged**
